const lgas = [
  "Aguata",
  "Anambra East",
  "Anaocha",
  "Awka North",
  "Anambra West",
  "Awka South",
  "Ayamelum",
  "Dunukofia",
  "Ekwusigo",
  "Idemili North",
  "Idemili South",
  "Ihiala",
  "Njikoka",
  "Nnewi North",
  "Nnewi South",
  "Ogbaru",
  "Onitsha North",
  "Onitsha South",
  "Orumba North",
  "Orumba South",
  "Oyi",
];

const polling_units = [
  "ACHINA   I",
  "ACHINA  II",
  "AGULUEZE CHUKWU",
  "AKPO",
  "AMESI",
  "EKWULOBIA  I",
  "EKWULOBIA  II",
  "EZINIFITE  I",
  "EZINIFITE  II",
  "IGBO-UKWU  I",
  "IGBO - UKWU  II",
  "IKENGA",
  "ISUOFIA",
  "NKPOLOGWU",
  "ORAERI",
  "UGA  I",
  "UGA II",
  "UMUCHU  I",
  "UMUCHU  II",
  "UMUONA",
];

export { lgas, polling_units };
